### ISSUE TITLE
getting an error on build

### ISSUE THREAD

**Issue by chancesmith** [themeteorchef/building-an-error-logger#1]
Getting an Exit code 8. Just me?

I opened code/ then:
`$ npm install`
`$ meteor`

result:
```
W20161211-14:33:31.876(-6)? (STDERR)
W20161211-14:33:31.877(-6)? (STDERR) /Users/XXXXUSERXXXX/.meteor/packages/meteor-tool/.1.1.13-modules.8.dy1j0t++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20161211-14:33:31.877(-6)? (STDERR) 						throw(ex);
W20161211-14:33:31.877(-6)? (STDERR) 						      ^
W20161211-14:33:31.899(-6)? (STDERR) TypeError: Cannot read property 'name' of undefined
W20161211-14:33:31.900(-6)? (STDERR)     at meteorInstall.server.accounts.email-templates.js (server/accounts/email-templates.js:2:22)
W20161211-14:33:31.900(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
W20161211-14:33:31.900(-6)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20161211-14:33:31.900(-6)? (STDERR)     at /Users/XXXXUSERXXXX/Downloads/building-an-error-logger-master/code/.meteor/local/build/programs/server/app/app.js:700:1
W20161211-14:33:31.900(-6)? (STDERR)     at /Users/XXXXUSERXXXX/Downloads/building-an-error-logger-master/code/.meteor/local/build/programs/server/boot.js:242:10
W20161211-14:33:31.900(-6)? (STDERR)     at Array.forEach (native)
W20161211-14:33:31.900(-6)? (STDERR)     at Function._.each._.forEach (/Users/XXXXUSERXXXX/.meteor/packages/meteor-tool/.1.1.13-modules.8.dy1j0t++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20161211-14:33:31.900(-6)? (STDERR)     at /Users/XXXXUSERXXXX/Downloads/building-an-error-logger-master/code/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

Is there something I'm missing?

I event tried to update npm and meteor. No dice. :(

**Comment by themeteorchef** [comment]
Hi Chance, we'll need to review this repo. 

In the short-term, the fix seems to be here:

```
TypeError: Cannot read property 'name' of undefined
W20161211-14:33:31.900(-6)? (STDERR)     at meteorInstall.server.accounts.email-templates.js (server/accounts/email-templates.js:2:22)
```

There's an undefined property name in the `email-templates.js` file that's tripping up the start up process. If you look in that file, it may just be a matter of a misplaced variable.

**Comment by chancesmith** [comment]
It looks like the variables are declared properly in `/server/accounts/email-templates.js`.

Does there need to be a `settings.json`?
https://blog.meteor.com/the-meteor-chef-making-use-of-settings-json-3ed5be2d0bad#.bfyyo3wle

...maybe that is why `name = settings.name` is failing?

**Comment by themeteorchef** [comment]
Hi @chancesmith :) Yes, that's the fix. Make sure to boot your server with your settings in tow like this: `meteor --settings settings-development.json`.
